### ISSUE TITLE
asyncapi is not a valid specification schema

### ISSUE THREAD

**Issue by DavidMeu** [RonnyPfannschmidt/prance#108]
asyncapi: "2.0.0"

Is not valid.
Recieving:
```
    raise ValidationError('Could not determine specification schema '
prance.ValidationError: Could not determine specification schema version!
```

**Comment by RonnyPfannschmidt** [comment]
asyncapi is  a different set of standards from openapi, for now i cant consider adding it

**Comment by RonnyPfannschmidt** [comment]
primary reason is that it needs new tools and has different properties from openapi in many ways

 it will take a while before i can allocate the time needed to deal with those

**Comment by RonnyPfannschmidt** [comment]
but to handle that feel free to add a actual feature request including more details
im going to close this bug report as its simply not fitting
