### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by jiaxian-lin** [RonnyPfannschmidt/prance#109]
i have some problem like this:
   my open_api file has this error:

prance.util.url.ResolutionError: Recursion reached limit of 1 trying to resolve 

but when i annotate the recursion part，then i has this error：
"File not found: ../open_api/Error-ModelName{namespace='java.lang', name='Void'}")

i really don't know why, can you help me ?

**Comment by RonnyPfannschmidt** [comment]
without more information on your files and the refs you use we cant say anything at all

can you provide a minimal example?

**Comment by RonnyPfannschmidt** [comment]
closing as lack of information
