### ISSUE TITLE
Requesting a new release tag for the change - update openapi-spec-validator NixOS/nixpkgs#193272

### ISSUE THREAD

**Issue by Milind-TW** [RonnyPfannschmidt/prance#139]
We can see that the fix for issue https://github.com/RonnyPfannschmidt/prance/issues/131 has been merged but not released yet.  

Requesting a new release tag for this change so that we can use the latest version in our pipelines.

_Originally posted by @Milind-TW in https://github.com/RonnyPfannschmidt/prance/issues/132#issuecomment-1303549292_

**Comment by RonnyPfannschmidt** [comment]
thanks forthe ping
https://github.com/RonnyPfannschmidt/prance/pull/140 will be needed in then i will release

**Comment by RonnyPfannschmidt** [comment]
https://pypi.org/project/prance/0.22.11.4.0/
