### ISSUE TITLE
HOMEDRIVE in the fs.py file causes an error

### ISSUE THREAD

**Issue by samih100** [RonnyPfannschmidt/prance#142]
https://github.com/RonnyPfannschmidt/prance/blob/181bf60c02866313c9b65b179c8ae8d5112e6273/prance/util/fs.py#L66

**Problem/bug**
The problem is on a Windows computer with a home folder that is shared as a network drive. This is standard practice in a Windows AD environment. If the client computer cannot connect to the home folder, prance validation fails and it's give assertion failure.

**Minimal Example Spec**
`
  File "C:\Program Files\workspace\lib\site-packages\prance\util\fs.py", line 70, in is_pathname_valid
    assert os.path.isdir(root_dirname)  # ...Murphy and her ironclad Law
AssertionError
`

**Fix**
The problem is fixed when the Python code uses the SYSTEMDRIVE instead of the HOMEDRIVE.
`
	        root_dirname = (
            os.environ.get("SYSTEMDRIVE", "C:")
            if sys.platform == "win32"
            else os.path.sep
        )
        assert os.path.isdir(root_dirname)  # ...Murphy and her ironclad Law
`

Homedrive vs systemdrive: https://superuser.com/questions/1279500/homedrive-vs-systemdrive

- The %systemdrive% (typically c:) is the partition with the %systemroot% (typically Windows) directory.
- %homedrive% is typically your network root profile directory, in an (Active Directory) Domain, it would reside on a server.

**Environment**
- OS: Windows 10
- Python version: 3.10.3
- Swagger/OpenAPI version used: OpenApi 3.0.1

**Comment by RonnyPfannschmidt** [comment]
closing as fixed by #143
