### ISSUE TITLE
support packaging v23

### ISSUE THREAD

**Issue by kbroch-rivosinc** [RonnyPfannschmidt/prance#145]
`prance 0.22.11.4.0 requires packaging~=21.3, but you have packaging 23.0 which is incompatible.`

**Comment by leifwalsh** [comment]
Now that [black 23 depends on packaging >=22.0](https://github.com/psf/black/blob/23.1.0/pyproject.toml#L68), the pinning of packaging in this package can cause pip's resolver to fail to find a solution for any project that's using an unqualified version of black together with prance (I have a case where this is happening with pip-tools). 

Using `pip-compile --resolver=backtracking` does find a solution, but it chooses to downgrade prance to 0.21.8.0, before prance added this pin.

**Comment by kbroch-rivosinc** [comment]
Thank you 🙏
