### ISSUE TITLE
pypi lists previous release as latest

### ISSUE THREAD

**Issue by robinmackaij** [RonnyPfannschmidt/prance#148]
On pypi, the most recent release (0.22.2.22.0) is not considered the latest release due to it's version number being lower than 0.22.11.4.0.

A `poetry update prance` does however update to .22.2.22.0 from 0.22.11.4.0 (so no more click version conflict with black while using the CLI extras, thanks for the quick fix!).

I can imagine pypi listing the previous version as latest can cause some confusion / issues.

**Comment by blowekamp** [comment]
I am getting a conflict due to old releases pinning of "packaging" package. This current release solves the issue, but is not automatically installed.

**Comment by RonnyPfannschmidt** [comment]
Thanks for the Ping ,it fell through the cracks, I'll try to get a release with correct versions Out this week if not today
