### ISSUE TITLE
Find someone to adopt prance maintainership/ownership

### ISSUE THREAD

**Issue by jfinkhaeuser** [RonnyPfannschmidt/prance#91]
I just came across the fact that the Python `cryptography` now has a hard dependency on Rust. While prance does not use this package, this breaks things elsewhere, and the maintainer of the package does not seem to accept this as an issue (see https://github.com/pyca/cryptography/issues/5799 ).

I can't decide what's right for this package, but it is sufficiently important for any applications using the internet that it effectively has infrastructure status. As such, this decision affects most of the Python ecosystem. Entire applications fail to update due to this decision, reminiscent of Node's left-pad debacle. Introducing dependency on an entirely new toolchain is just too big of a change for e.g. embedded applications, or any platform that is not a tier 1 development target for Rust. In my (not so) humble opinion, this was a bad decision, the ramifications of which will become apparent in the next few months.

However, I don't have the spare energy to fight that. My personal consequence is that I will drop support for prance as of right now. That brings the package up for adoption by anyone willing to put in the effort. Let me know if you're willing to in a comment.

**Comment by jfinkhaeuser** [comment]
@RonnyPfannschmidt because you were actively interested.

**Comment by jfinkhaeuser** [comment]
@Glutexo  ?

**Comment by RonnyPfannschmidt** [comment]
Im reluctant at the moment for any type of adoption, as im not directly using the library myself, but instead ran into a couple of issues due to bugs / incomplete features in this library. 

I'll bring up the issue with the relevant team in today's sync.

**Comment by jfinkhaeuser** [comment]
Thanks! I'm just trying to tag people that might have an interest.

**Comment by RonnyPfannschmidt** [comment]
I brought it up with the affected team, a decision will be made soon

**Comment by jfinkhaeuser** [comment]
Thank you very much!

**Comment by Glutexo** [comment]
I can’t decide that for myself. But Red Hat may be interested in an adoption and further maintenance. Let’s see what @RonnyPfannschmidt’s team comes with. cc @gmcculloug

**Comment by jfinkhaeuser** [comment]
Thank you as well!

**Comment by RonnyPfannschmidt** [comment]
we started some discussions and are interested, we are currently figuring how to make sure this will stay alive in a good way and won't just bit rot under a new name

**Comment by Goldziher** [comment]
Jazz band is also an option, or snok? @sondrelg

**Comment by RonnyPfannschmidt** [comment]
at first glance none of those are well suited to take a project that currently is not maintained, snok has a dead/empty description since a year and jazz band is no charity either

**Comment by sondrelg** [comment]
Don't judge a book by it's cover 🤓 Out of curiosity, what description is missing?

We use this library as a core dependency for [drf-openapi-tester](https://github.com/snok/drf-openapi-tester), so it could be a good fit. At the same time, we're not really looking to take on more projects at the moment (who is), but if someone else wanted to actively maintain it *under* the snok umbrella, @jonasks and me would be happy to help in a slightly more passive capacity.

**Comment by RonnyPfannschmidt** [comment]
its absolutely unclear what the goal/expectations are, so from my pov its jsut a random undefined name with some projects under it

not something i would trust

**Comment by RonnyPfannschmidt** [comment]
i never talked about commercialized, but all you have as the starting point is a logo and a name,
"review the code of all the projects to see the quality as i cant give you a better indication" seems off the wrong foot to me and perfectly demonstrates why i personally wont trust the org as a starting point (while happy to be wrong)

i'm well aware of jazzband, their guidelines, which is precisely why i brushed them off for now, as currently the project has no maintainer

the "where" is pointless if the "who" and "how" is not determined, just bit-rotting under a new name would be pointless

**Comment by Goldziher** [comment]
@jfinkhaeuser I guess you need to make some decisions.

**Comment by RonnyPfannschmidt** [comment]
@jfinkhaeuser :  @Glutexo and me are now at a point where we'd volunteer our hands to do the maintainership

**Comment by jfinkhaeuser** [comment]
Thank you for this!

To summarize, I'm reading this discussion as:
- Contact JazzBand, see what they say.
- snok, with @RonnyPfannschmidt and @Glutexo as maintainers.

Does that seem about right?

**Comment by RonnyPfannschmidt** [comment]
We aren't related to snok as of now,

**Comment by sondrelg** [comment]
Feel free to leave Snok out of the equation - we were only offering to house the project in the event that someone like @RonnyPfannschmidt would want to be the primary maintainer but have someone to help out from time to time. This doesn't seem to be the case.

**Comment by RonnyPfannschmidt** [comment]
i want to enable C4 style development with a number of people being able to quickly push releases via automation

**Comment by jfinkhaeuser** [comment]
Well in that case, it's simple - one candidate and one I'd have to convince still :)

**Comment by RonnyPfannschmidt** [comment]
@jfinkhaeuser thanks, i'm starting the process of the busybody work of the ownership transfer  then ^^

**Comment by jezdez** [comment]
> at first glance none of those are well suited to take a project that currently is not maintained, snok has a dead/empty description since a year and jazz band is no charity either

Hi Ronny, let me know if you want to chat about transferring this project to Jazzband, I saw your proposal and I'm interested in what you mean with "jazz band is no charity either"?

**Comment by RonnyPfannschmidt** [comment]
@jezdez happy to as i jsut started to pick things up

what i mean by no charity either - you are all hardworking and time-stripped individuals that banded together to manage the projects
throwing in a project that doesn't have a lead seems like a disservice to me, the wording "not a charity either" is in hindsight neither detailed enough nor does it do the good work all of you do justice

**Comment by jezdez** [comment]
> @jezdez happy to as i jsut started to pick things up
> 
> what i mean by no charity either - you are all hardworking and time-stripped individuals that banded together to manage the projects
> throwing in a project that doesn't have a lead seems like a disservice to me, the wording "not a charity either" is in hindsight neither detailed enough nor does it do the good work all of you do justice

Understood, thanks for elaborating, yeah, having active project leads is essential in my experience just like the regularl GitHub development experience. Jazzband simply makes it easier to be maintainers with a few automations, standards and features to on-board new people.
