### ISSUE TITLE
👥 @Glutexo does not have write permissions to the repository

### ISSUE THREAD

**Issue by Glutexo** [RonnyPfannschmidt/prance#97]
## Expected Behaviour
@Glutexo can merge pull requests and do stuff.

### Minimal Example Spec
Come to a pull request, e.g. #96, fix the failing pipeline, restart the tests by pushing to the branch, approve, merge.

## Actual Behaviour
@Glutexo can not merge pull requests and do stuff.

## Steps to Reproduce
Open a pull request. See that there is no merge button. See a message saying that write permissions are missing.

## Environment
- GitHub
- Logged in as @Glutexo

**Comment by Glutexo** [comment]
May I ask @RonnyPfannschmidt to take a look at this?

**Comment by RonnyPfannschmidt** [comment]
already fixed
